motion_server_node:
  ros__parameters:
    move_group_name: "manipulator"
    end_effector_name: "azrael/tcp"
    base_link_name: "azrael/base_link"
    joint_names:
      - 'azrael/shoulder_pan_joint'
      - 'azrael/shoulder_lift_joint'
      - 'azrael/elbow_joint'
      - 'azrael/wrist_1_joint'
      - 'azrael/wrist_2_joint'
      - 'azrael/wrist_3_joint'
    cartesian_max_step: 0.001 #25
    cartesian_fraction_threshold: 0.9
    cartesian_jump_threshold: 0.0
    cartesian_avoid_collisions: True
    max_velocity: 0.1
    max_acceleration: 0.1
    planner_id: RRTConnect
    allowed_planning_time: 5.0
    virtual_end_effector: "azrael/tcp"
